language: node_js
node_js:
- stable
script:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
- chmod 0600 deploy_rsa
- eval $(ssh-agent -s)
- ssh-add deploy_rsa
- travis_wait ssh -o StrictHostKeyChecking=no lara@larapollehn.de "cd tinylink && git pull && docker-compose up -d --build"

