version: "3"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
     - 3011:80

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
     - 3012:3000
    depends_on:
     - database

  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tinylink
    volumes:
    - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
