CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
username VARCHAR(255) UNIQUE NOT NULL,
password_hash VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
valid BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS forgot_password_tokens (
id SERIAL PRIMARY KEY,
token VARCHAR(255) UNIQUE NOT NULL,
user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS confirm_account_tokens (
id SERIAL PRIMARY KEY,
token VARCHAR(255) UNIQUE NOT NULL,
user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS links (
id SERIAL PRIMARY KEY,
shorturl VARCHAR(10) UNIQUE NOT NULL,
originalurl TEXT NOT NULL,
visit_count BIGINT DEFAULT 0 NOT NULL,
user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS clicks (
id SERIAL PRIMARY KEY,
link_id BIGINT REFERENCES links(id) ON DELETE CASCADE,
clicked_at TIMESTAMP not null DEFAULT NOW()
);