site_name: tinylink's documentation
theme:
  name: material
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Learning Process:
      - Day 2: tag2.md
  - Tech Stack: techstack.md
  - System Design: systemdesign.md